api & ui: mattermost migration

diff --git a/api/migration/update b/api/migration/update
--- a/api/migration/update
+++ b/api/migration/update
@@ -47,14 +47,6 @@ set_migration_status() {
 if [[ "$app_id" == "nethserver-nextcloud" ]]; then
     if [[ "$action" == "start" ]]; then
         set_migration_status $app_id "syncing"
-
-        # connect to NS7 DC //// remove
-        # /usr/share/nethesis/nethserver-ns8-migration/apps/ldapproxy/export
-
-        # if [ $? -gt 0 ]; then
-        #     error "EventFailed" "See /var/log/messages"
-        # fi
-
         /sbin/e-smith/signal-event -j nethserver-ns8-migration-export-app nextcloud
 
         if [ $? -gt 0 ]; then
@@ -65,7 +57,6 @@ if [[ "$app_id" == "nethserver-nextcloud" ]]; then
         set_migration_status $app_id "migrating"
     elif [[ "$action" == "sync" ]]; then
         set_migration_status $app_id "syncing"
-
         /sbin/e-smith/signal-event -j nethserver-ns8-migration-export-app nextcloud
 
         if [ $? -gt 0 ]; then
@@ -88,7 +79,6 @@ if [[ "$app_id" == "nethserver-nextcloud" ]]; then
 elif [[ "$app_id" == "account-provider" ]]; then
     if [[ "$action" == "start" ]]; then
         set_migration_status $app_id "syncing"
-
         /sbin/e-smith/signal-event -j nethserver-ns8-migration-export-app ldapproxy
 
         if [ $? -gt 0 ]; then
@@ -106,6 +96,37 @@ elif [[ "$app_id" == "account-provider" ]]; then
         #     error "EventFailed" "See /var/log/messages"
         # fi
         # fi
+    fi
+elif [[ "$app_id" == "nethserver-mattermost" ]]; then
+    if [[ "$action" == "start" ]]; then
+        set_migration_status $app_id "syncing"
+        /sbin/e-smith/signal-event -j nethserver-ns8-migration-export-app mattermost
+
+        if [ $? -gt 0 ]; then
+            error "EventFailed" "See /var/log/messages"
+        fi
+
+        set_migration_status $app_id "migrating"
+    elif [[ "$action" == "sync" ]]; then
+        set_migration_status $app_id "syncing"
+        /sbin/e-smith/signal-event -j nethserver-ns8-migration-export-app mattermost
+
+        if [ $? -gt 0 ]; then
+            set_migration_status $app_id "migrating"
+            error "EventFailed" "See /var/log/messages"
+        fi
+
+        set_migration_status $app_id "migrating"
+    elif [[ "$action" == "finish" ]]; then
+        set_migration_status $app_id "syncing"
+        /sbin/e-smith/signal-event -j nethserver-ns8-migration-migrate-app mattermost
+
+        if [ $? -gt 0 ]; then
+            set_migration_status $app_id "migrating"
+            error "EventFailed" "See /var/log/messages"
+        fi
+
+        set_migration_status $app_id "migrated"
     fi
 fi
 
