api&ui: uninstall app from backend; fix log file

diff --git a/api/migration/update b/api/migration/update
--- a/api/migration/update
+++ b/api/migration/update
@@ -51,7 +51,7 @@ fi
 if [ "$action" == "start" ] || [ "$action" == "sync" ]; then
     set_migration_status $app_id "syncing"
 
-    /usr/share/nethesis/nethserver-ns8-migration/apps/$app/export >> /var/log/ns8-migration.log
+    /usr/share/nethesis/nethserver-ns8-migration/apps/$app/export &>>/var/log/ns8-migration.log
     if [ $? -gt 0 ]; then
         set_migration_status $app_id "migrating"
         error "ApiFailed" "/usr/share/nethesis/nethserver-ns8-migration/apps/$app/export failed"
@@ -62,10 +62,33 @@ elif [[ "$action" == "finish" ]]; then
     set_migration_status $app_id "syncing"
 
     # if needed, pass additional migration configurations to migrate script (e.g. virtual host for webapps, IP address for AD)
-    echo "$migration_config" | /usr/share/nethesis/nethserver-ns8-migration/apps/$app/migrate >> /var/log/ns8-migration.log
+    echo "$migration_config" | /usr/share/nethesis/nethserver-ns8-migration/apps/$app/migrate &>>/var/log/ns8-migration.log
     if [ $? -gt 0 ]; then
         set_migration_status $app_id "migrating"
         error "ApiFailed" "/usr/share/nethesis/nethserver-ns8-migration/apps/$app/migrate failed"
+    fi
+
+    if [[ "$app_id" != "account-provider" ]]; then
+        # uninstall app
+        output=$(echo "{\"action\": \"list-removed\", \"packages\": [\"$app_id\"]}" | /usr/libexec/nethserver/api/system-packages/read)
+        packages=$(echo $output | jq -r '.packages')
+
+        echo "{\"action\": \"remove\", \"packages\": $packages}" | /usr/libexec/nethserver/api/system-packages/update
+        if [ $? -gt 0 ]; then
+            set_migration_status $app_id "migrating"
+            error "ApiFailed" "/usr/libexec/nethserver/api/system-packages/update failed"
+        fi
+
+        js_array=$(echo $packages | jq -r ".[]")
+        # define bash array
+        declare -a packages_arr=($js_array)
+
+        for package in "${packages_arr[@]}"; do
+            # remove pin and shortcut of uninstalled packages
+            echo "{\"action\": \"remove-pin\", \"name\": \"$package\"}" | /usr/libexec/nethserver/api/system-apps/update
+            echo "{\"action\": \"remove-shortcut\", \"name\": \"$package\"}" | /usr/libexec/nethserver/api/system-apps/update
+        done
+
     fi
 
     set_migration_status $app_id "migrated"
