api & ui: logout from ns8 cluster

diff --git a/api/connection/update b/api/connection/update
--- a/api/connection/update
+++ b/api/connection/update
@@ -25,34 +25,58 @@
 # read json from stdin
 data=$(cat /dev/stdin)
 
+action=$(echo $data | jq -r '.action')
 host=$(echo $data | jq -r '.Host')
 user=$(echo $data | jq -r '.User')
 password=$(echo $data | jq -r '.Password')
 tls_verify=$(echo $data | jq -r '.TLSVerify')
 
-/sbin/e-smith/config setprop ns8 Host "$host" User "$user" Password "$password" TLSVerify "$tls_verify"
+# //// remove
+# /sbin/e-smith/config setprop ns8 Host "$host" User "$user" Password "$password" TLSVerify "$tls_verify"
+# if [ $? -gt 0 ]; then
+#     invalid_error
+# fi
 
-if [ $? -gt 0 ]; then
-    invalid_error
-fi
+if [[ "$action" == "login" ]]; then
+    # execute ns8-join
 
-# execute ns8-join
+    if [ "$tls_verify" = "disabled" ]; then
+        /usr/bin/ns8-join --no-tlsverify "$host" "$user" "$password"
+    else
+        /usr/bin/ns8-join "$host" "$user" "$password"
+    fi
 
-if [ "$tls_verify" = "disabled" ]; then
-    /usr/bin/ns8-join --no-tlsverify "$host" "$user" "$password"
-else
-    /usr/bin/ns8-join "$host" "$user" "$password"
-fi
+    if [ $? -gt 0 ]; then
+        error "CommandFailed" "See /var/log/messages"
+    fi
 
-if [ $? -gt 0 ]; then
-    error "EventFailed" "See /var/log/messages"
-fi
+    # signal event
 
-# signal event
+    /sbin/e-smith/signal-event -j nethserver-ns8-migration-save
+    if [ $? -gt 0 ]; then
+        error "EventFailed" "See /var/log/messages"
+    fi
 
-/sbin/e-smith/signal-event -j nethserver-ns8-migration-save
-if [ $? -gt 0 ]; then
-    error "EventFailed" "See /var/log/messages"
+elif [[ "$action" == "logout" ]]; then
+    # disconnect from ns8 cluster
+
+    # //// TODO invoke remove-node action on ns8
+
+    /sbin/e-smith/config setprop ns8 Host "" User "" Password "" TLSVerify enabled
+    /sbin/e-smith/config setprop agent status disabled
+    /sbin/e-smith/config setprop wg-quick@wg0 status disabled Address "" RemoteEndpoint "" RemoteKey ""
+
+    rm -f /var/lib/nethserver/agent/agent.env
+    rm -f /var/lib/nethserver/agent/environment
+
+    # //// TODO delete app config files, e.g. /var/lib/nethserver/agent/mattermost.json ?
+
+    # signal event
+
+    /sbin/e-smith/signal-event -j nethserver-ns8-migration-save
+    if [ $? -gt 0 ]; then
+        error "EventFailed" "See /var/log/messages"
+    fi
 fi
 
 success
